{% set data = load_setup_py_data() %}

package:
  name: adam
  version: {{ data.get('version') }}

source:
  path: ..

requirements:
  build:
    - python
    - requests
    - pandas
    - pytest
    - pytest-cov
    - coveralls
    - flake8
    - nbconvert
  run:
    - python
    - requests
    - pandas

test:
  imports:
    - adam
  commands:
    - pwd

build:
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

about:
  home: https://adam.asteroid-institute.org
  license: BSD
  summary: 'Asteroid Institute ADAM'
  description: |
    This package installs the ADAM Client Libraries
